#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define MAX 10 // total number of books each student can issue

typedef struct book{
        char name[100];
        int id;
        int status;//available or not?
        struct book* next;
}BOOK;

typedef struct student{
        char name[50];
        int roll;
        char status[MAX];//array of book ids issued
        struct student* next;
}STUDENT;

//utility
void initialize(BOOK** b);//initializes pointers with null
int countSize(FILE* fp);//returns number of lines in the file

//book functions
void printBookList(BOOK* list);//prints book list in console
void updateBookFile(BOOK* list);//copies book list to books.txt
void createBook(BOOK** list);//adds new book from console to list--> uses addBook()
void addBook(BOOK** list,BOOK* newbook);//adds new book with given newbook data
void deleteBook(BOOK** list,int id);//deletes book with id
BOOK* readBooks();//returns pointer to head node of BOOK list generated by reading input file
int isAvailable(BOOK* list,int id);//returns 1 if available ; 0 if not; 
int findBook(BOOK* list,int id);//returns 1 if found; 0 if not!


 void initialize(BOOK** b){
         *b = NULL;
 }
int countSize(FILE* fp){
        int count = 0;
        while(!feof(fp)){
                if(fgetc(fp) == '\n')
                count++;
        }
        printf("count: %d\n",count); // test
        return count;
}
void printBookList(BOOK* list){
        if(list == NULL){
                printf("Book list empty!!!\n");
                return;
        }
        printf("BOOK LIST:\n");
        while(list->next != NULL){
                printf("%-3d %-50s %d\n",list->id,list->name,list->status);

                list = list->next;
        }
        printf("%-3d %-50s %d\n",list->id,list->name,list->status);
}
void updateBookFile(BOOK* list){
        FILE* fp;
        if((fp = fopen("books.txt","w"))){
        while(list->next != NULL){
                fprintf(fp,"%-3d %-50s %d\n",list->id,list->name,list->status);

                list = list->next;
        }
        fprintf(fp,"%-3d %-50s %d\n",list->id,list->name,list->status);
        }
        else{
                printf("cant open file!");
                return;
        }
}
void createBook(BOOK** list){
        BOOK* temp = *list;
        BOOK* newbook = (BOOK*)malloc(sizeof(BOOK));
        printf("enter book name: ");
        scanf("%[^\n]s",newbook->name);
        printf("\nenter id: ");
        scanf("%d",&newbook->id);
        //validate book id
        if(newbook->id == 0){
                printf("id cannot be 0!!\n");
                return;
        }
        while(temp != NULL){
                if(temp->id == newbook->id){
                        printf("id already taken by: %s\n",temp->name);
                        return;
                }
                temp = temp->next;
        }
        
        newbook->status = 1;//available
        newbook->next = NULL;
        addBook(list,newbook);
        /*
        if(*list == NULL){
                *list = newbook;
        }
        else{
                temp = *list;
                while(temp->next!=NULL){
                        temp = temp->next;
                }
                temp->next = newbook;
        }
        */
        updateBookFile(*list);
}

void addBook(BOOK** list,BOOK* newbook){
        if(*list == NULL){
                *list = newbook;
        }
        else{
                BOOK* temp = *list;
                while(temp->next!=NULL){
                        temp = temp->next;
                }
                temp->next = newbook;
        }
        
}

//delete with id
void deleteBook(BOOK** list,int id){
        if((*list) == NULL){
                printf("list empty!");
                return;
        }
        if((*list)->id == id){
                
                printf("deleted book: %s id: %d\n",(*list)->name,(*list)->id);
                BOOK* todelete = *list;
                *list = (*list)->next;
                free(todelete);
                todelete = NULL;
        }
        else{
                BOOK* temp = *list;
                int check=0;
                while(temp->next != NULL){
                        if(temp->next->id == id){
                                BOOK* todelete = temp->next; 
                                printf("deleted book: %s id: %d\n",todelete->name,id);
                                temp->next = todelete->next;
                                free(todelete);
                                todelete = NULL;
                                check++;
                                break;
                        }
                        temp = temp->next;
                }
                if(check == 0)
                printf("id: %d not found in BOOK list!\n",id);
        }
        updateBookFile(*list);
}
BOOK* readBooks(){
        FILE* fp;
        if((fp = fopen("books.txt","r"))){
        int i=0,size = countSize(fp);
        BOOK* blist;
        initialize(&blist);
        fseek(fp,0,SEEK_SET);
        while(!feof(fp)){ 
                BOOK* book = (BOOK*)malloc(sizeof(BOOK));
                fscanf(fp,"%d",&book->id);
                if(book->id == 0)
                        break;
                        
                 while(fgetc(fp) == ' ');
                fseek(fp,-1,SEEK_CUR); 

                fscanf(fp,"%22[^\n]s",book->name);
                fscanf(fp,"%d",&book->status);
                book->next = NULL;
                addBook(&blist,book);
                i++;
        }
        return blist;
        fclose(fp);
        }
        else{
                printf("cant open file!");
                return NULL;
        }
}
int isAvailable(BOOK* list,int id){
        while(list != NULL){
                if(list->id == id){
                        return list->status;
                }
                list = list->next;
        }
        printf("book with id: %d not found!\n",id);
        return 0;
}
int findBook(BOOK* list,int id){
         while(list != NULL){
                if(list->id == id){
                        return 1;
                }
                list = list->next;
        }
        return 0;
}

/*********************STUDENT functions***********************/
//student functions
 void initializeStudent(STUDENT** s);
 void statusToInt(char status[],int stat[]);//converts status string to int array of size MAX
 void printStatus(int status[]);//prints status array until 0 found!
 void addStudent(STUDENT** list,STUDENT* newstudent);//generates student list at runtime
 STUDENT* readStudents(); // reads data from file and calls addStudent()
 void printStudentList(STUDENT* list);// prints student list

 
/*********************STUDENT functions***********************/
 void initializeStudent(STUDENT** s){
         *s = NULL;
 }
 void statusToInt(char status[],int stat[]){
         int j = 0;
         for(int i=0;i<strlen(status);i++){
                 
                 
                 if(status[i] >= 48 && status[i] <= 57){
                         //printf("%c %d\n",status[i],j);
                         stat[j] = status[i] - 48;
                         j++;
                         if(j == MAX)
                                break;
                 }
                 //if(status[j] == '\0')
                        //break;
         }
         /*
         for(int i=0;i<MAX;i++){
                 printf("%d ",stat[i]);
                 if(stat[i] == 0)
                        break;
         }
         printf("\n");
         */
 }
 void printStatus(int status[]){

         for(int i=0;i<MAX;i++){
                 printf("%d ",status[i]);
                 if(status[i] == 0)
                        break;
         }
         printf("\n");
 }
void addStudent(STUDENT** list,STUDENT* newstudent){
        if(*list == NULL){
                *list = newstudent;
        }
        else{
                STUDENT* temp = *list;
                while(temp->next!=NULL){
                        temp = temp->next;
                }
                temp->next = newstudent;
        }
        
}
STUDENT* readStudents(){
        FILE* fp;
        if((fp = fopen("students.txt","r"))){
        int i=0,size = countSize(fp);
        
        STUDENT* slist;
        initializeStudent(&slist);
        fseek(fp,0,SEEK_SET);
        while(!feof(fp)){ 
                STUDENT* student = (STUDENT*)malloc(sizeof(STUDENT));
                fscanf(fp,"%d",&student->roll);
                if(student->roll == 0)
                        break;
                fscanf(fp,"%13[^\n]s",student->name);
                 /*       
                 while(fgetc(fp) == ' ');
                fseek(fp,-1,SEEK_CUR); 
                */
                 fscanf(fp,"%10[^\n]s",student->status);
                
                
                student->next = NULL;
                addStudent(&slist,student);
                i++;
        }
        return slist;
        fclose(fp);
        }
        else{
                printf("cant open file!");
                return NULL;
        }
}
void printStudentList(STUDENT* list){
       
        if(list == NULL){
                printf("Student list empty!!!\n");
                return;
        }
        printf("STUDENT LIST:\n");
        while(list != NULL){
                printf("roll:%-3d name:%-50s status:",list->roll,list->name);
                //int size = strlen(list->status);
                //printf("%s",list->status);
                int stat[MAX];
                statusToInt(list->status,stat);
                printStatus(stat);
                printf("\n");
                list = list->next;
        }
        
}
int main(void) {
  //BOOK* blist;
  //blist = readBooks();
  STUDENT* slist;
  //printBookList(NULL);
  //createBook(&blist);
  //printBookList(blist);
  //deleteBook(&blist,22);
  //printBookList(blist);
  //printf("%d\n",isAvailable(blist,22));
  slist = readStudents();
  printStudentList(slist);
  return 0;}